/**
 * Seed catalogue for Akrem Mobile — prices in DZD, tuned to the Algerian
 * street market (2026). 18 smartphones + 3 laptops + 5 accessories.
 * Image URLs point at stable images.unsplash.com photos; the UI falls back to
 * a styled placeholder when an image cannot be loaded.
 */
const img = (id) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=80`

export const PRODUCTS = [
  // ---------------------------------------------------------------- smartphones
  {
    name: 'آيفون 15 برو 256GB',
    name_fr: 'iPhone 15 Pro 256 Go',
    brand: 'Apple',
    category: 'smartphones',
    price_dzd: 289000,
    old_price_dzd: 305000,
    description: 'آيفون 15 برو بحجم 6.1 بوصة، هيكل تيتانيوم وشريحة A17 Pro، مثالي للتصوير الاحترافي والأداء العالي.',
    description_fr: "iPhone 15 Pro 6,1 pouces, chassis en titane et puce A17 Pro : photo pro et performances de pointe.",
    image_url: img('1511707171634-5f897ff02aa9'),
    specs: { ram: '8 Go', storage: '256 Go', screen: '6.1"', battery: '3274 mAh' },
    stock: 12,
    rating: 4.8,
    is_featured: 1,
  },
  {
    name: 'آيفون 14 128GB',
    name_fr: 'iPhone 14 128 Go',
    brand: 'Apple',
    category: 'smartphones',
    price_dzd: 199000,
    old_price_dzd: null,
    description: 'آيفون 14 بشريحة A15 Bionic، كاميرا 12 ميجابكسل وشاشة Super Retina XDR، أداء موثوق وسعر في المتناول.',
    description_fr: "iPhone 14 avec puce A15 Bionic, appareil photo 12 MP et écran Super Retina XDR.",
    image_url: img('1601784551446-20c9e07cdbdb'),
    specs: { ram: '6 Go', storage: '128 Go', screen: '6.1"', battery: '3279 mAh' },
    stock: 20,
    rating: 4.7,
    is_featured: 1,
  },
  {
    name: 'سامسونج جالكسي S24 ألترا 256GB',
    name_fr: 'Samsung Galaxy S24 Ultra 256 Go',
    brand: 'Samsung',
    category: 'smartphones',
    price_dzd: 319000,
    old_price_dzd: 345000,
    description: 'قلم S Pen، كاميرا رباعية 200 ميجابكسل وشاشة 6.8 بوصة بمعدل تحديث 120Hz. رائد الفئة.',
    description_fr: "S Pen, quadruple capteur 200 MP et écran 6,8 pouces à 120 Hz : le référence du haut de gamme.",
    image_url: img('1556656793-08538906a9f8'),
    specs: { ram: '12 Go', storage: '256 Go', screen: '6.8"', battery: '5000 mAh' },
    stock: 9,
    rating: 4.9,
    is_featured: 1,
  },
  {
    name: 'سامسونج جالكسي A55 128GB',
    name_fr: 'Samsung Galaxy A55 128 Go',
    brand: 'Samsung',
    category: 'smartphones',
    price_dzd: 78000,
    old_price_dzd: 85000,
    description: 'هاتف متوسط الفئة بإطار معدني، شاشة AMOLED ناعمة وكاميرا ثلاثية ممتازة للتصوير اليومي.',
    description_fr: "Milieu de gamme à châssis métal, écran AMOLED fluide et triple capteur très polyvalent.",
    image_url: img('1585060544812-6b45742d762f'),
    specs: { ram: '8 Go', storage: '128 Go', screen: '6.6"', battery: '5000 mAh' },
    stock: 34,
    rating: 4.5,
    is_featured: 1,
  },
  {
    name: 'سامسونج جالكسي A15 128GB',
    name_fr: 'Samsung Galaxy A15 128 Go',
    brand: 'Samsung',
    category: 'smartphones',
    price_dzd: 42000,
    old_price_dzd: null,
    description: 'خيار اقتصادي موثوق بشاشة 90Hz وبطارية 5000mAh، مثالي للاستعمال اليومي والدراسة.',
    description_fr: "Option économique fiable : écran 90 Hz, batterie 5000 mAh, ideal au quotidien.",
    image_url: img('1546054454-aa26e2b734c7'),
    specs: { ram: '6 Go', storage: '128 Go', screen: '6.5"', battery: '5000 mAh' },
    stock: 48,
    rating: 4.2,
    is_featured: 0,
  },
  {
    name: 'شاومي ريدمي نوت 13 برو 256GB',
    name_fr: 'Xiaomi Redmi Note 13 Pro 256 Go',
    brand: 'Xiaomi',
    category: 'smartphones',
    price_dzd: 62000,
    old_price_dzd: 69000,
    description: 'كاميرا 200 ميجابكسل، شحن فائق 67W وشاشة AMOLED 120Hz. أفضل قيمة مقابل السعر.',
    description_fr: "Capteur 200 MP, charge rapide 67 W et AMOLED 120 Hz : le meilleur rapport qualité-prix.",
    image_url: img('1567581935884-3349723552ca'),
    specs: { ram: '8 Go', storage: '256 Go', screen: '6.67"', battery: '5100 mAh' },
    stock: 27,
    rating: 4.6,
    is_featured: 1,
  },
  {
    name: 'شاومي 14 256GB',
    name_fr: 'Xiaomi 14 256 Go',
    brand: 'Xiaomi',
    category: 'smartphones',
    price_dzd: 145000,
    old_price_dzd: null,
    description: 'معالج Snapdragon 8 Gen 3، كاميرات Leica ثلاثية وشحن 90W. رائد من شاومي بحجم مدمج.',
    description_fr: "Snapdragon 8 Gen 3, triple optique Leica et charge 90 W : le flagship compact de Xiaomi.",
    image_url: img('1574944985070-8f3ebc6b79d2'),
    specs: { ram: '12 Go', storage: '256 Go', screen: '6.36"', battery: '4610 mAh' },
    stock: 7,
    rating: 4.7,
    is_featured: 0,
  },
  {
    name: 'شاومي ريدمي 13C 128GB',
    name_fr: 'Xiaomi Redmi 13C 128 Go',
    brand: 'Xiaomi',
    category: 'smartphones',
    price_dzd: 29000,
    old_price_dzd: 32000,
    description: 'هاتف بسعر منخفض، شاشة 90Hz وبطارية تدوم يومين كاملين — نقطة دخول ممتازة.',
    description_fr: "Entrée de gamme à petit prix : écran 90 Hz et deux jours d'autonomie.",
    image_url: img('1592750475338-74b7b21085ab'),
    specs: { ram: '4 Go', storage: '128 Go', screen: '6.74"', battery: '5000 mAh' },
    stock: 55,
    rating: 4.1,
    is_featured: 0,
  },
  {
    name: 'أوبو رينو 11 F 5G',
    name_fr: 'Oppo Reno 11 F 5G',
    brand: 'Oppo',
    category: 'smartphones',
    price_dzd: 56000,
    old_price_dzd: null,
    description: 'تصميم أنيق وزجاج حماية، كاميرا 64 ميجابكسل وشحن 67W مع شاشة AMOLED.',
    description_fr: "Design soigné, verre de protection, capteur 64 MP, AMOLED et charge 67 W.",
    image_url: img('1592899677977-9c10ca588bbd'),
    specs: { ram: '8 Go', storage: '256 Go', screen: '6.7"', battery: '5000 mAh' },
    stock: 18,
    rating: 4.4,
    is_featured: 0,
  },
  {
    name: 'أوبو A78 128GB',
    name_fr: 'Oppo A78 128 Go',
    brand: 'Oppo',
    category: 'smartphones',
    price_dzd: 38000,
    old_price_dzd: 42000,
    description: 'هاتف أنيق بسعر في المتناول، بطارية تدوم طويلاً وواجهة ColorOS سلسة.',
    description_fr: "Élégant et abordable, longue autonomie et interface ColorOS fluide.",
    image_url: img('1625842268584-8f3296236761'),
    specs: { ram: '8 Go', storage: '128 Go', screen: '6.43"', battery: '5000 mAh' },
    stock: 23,
    rating: 4.2,
    is_featured: 0,
  },
  {
    name: 'ريلمي C55',
    name_fr: 'Realme C55',
    brand: 'Realme',
    category: 'smartphones',
    price_dzd: 33000,
    old_price_dzd: null,
    description: 'كاميرا 64 ميجابكسل، شحن 33W وشاشة 90Hz بسعر في المتناول.',
    description_fr: "Capteur 64 MP, charge 33 W et écran 90 Hz à prix doux.",
    image_url: img('1633269676068-59c8d2e0f6dd'),
    specs: { ram: '6 Go', storage: '128 Go', screen: '6.72"', battery: '5000 mAh' },
    stock: 31,
    rating: 4.1,
    is_featured: 0,
  },
  {
    name: 'تكنو سبارك 20 برو',
    name_fr: 'Tecno Spark 20 Pro',
    brand: 'Tecno',
    category: 'smartphones',
    price_dzd: 27000,
    old_price_dzd: 29500,
    description: 'شاشة AMOLED وكاميرا 108 ميجابكسل، أفضل نسبة سعر إلى مواصفات في فئته.',
    description_fr: "AMOLED, capteur 108 MP : le meilleur rapport caractéristiques/prix de sa gamme.",
    image_url: img('1616348436168-de43ad0db179'),
    specs: { ram: '8 Go', storage: '256 Go', screen: '6.78"', battery: '4800 mAh' },
    stock: 40,
    rating: 4.0,
    is_featured: 0,
  },
  {
    name: 'تكنو كامون 30 256GB',
    name_fr: 'Tecno Camon 30 256 Go',
    brand: 'Tecno',
    category: 'smartphones',
    price_dzd: 39000,
    old_price_dzd: null,
    description: 'هاتفتصوير بقدرة 50 ميجابكسل للملء والشبكات، مع شاشة AMOLED أنيقة.',
    description_fr: "Specialisé selfie : 50 MP pour les portraits et les groupes, écran AMOLED élégant.",
    image_url: img('1565849904461-04a58ad377e0'),
    specs: { ram: '8 Go', storage: '256 Go', screen: '6.78"', battery: '5000 mAh' },
    stock: 26,
    rating: 4.2,
    is_featured: 0,
  },
  {
    name: 'أونور X9b',
    name_fr: 'Honor X9b',
    brand: 'Honor',
    category: 'smartphones',
    price_dzd: 59000,
    old_price_dzd: 64000,
    description: 'شاشة منحنية 6.78 بوصة مقاومة للكسر وبطارية 5800mAh مع شحن 35W.',
    description_fr: "Écran incurvé 6,78 pouces résistant aux chutes, batterie 5800 mAh et charge 35 W.",
    image_url: img('1544244015-0df4b3ffc6b0'),
    specs: { ram: '8 Go', storage: '256 Go', screen: '6.78"', battery: '5800 mAh' },
    stock: 15,
    rating: 4.3,
    is_featured: 0,
  },
  {
    name: 'انفينيكس نوت 40 برو',
    name_fr: 'Infinix Note 40 Pro',
    brand: 'Infinix',
    category: 'smartphones',
    price_dzd: 45000,
    old_price_dzd: 49000,
    description: 'شحن لاسلكي 45W وشاشة منحنية AMOLED، أداء سلس للألعاب والتطبيقات.',
    description_fr: "Charge sans fil 45 W, AMOLED incurvé et fluidité en jeu comme en multitâche.",
    image_url: img('1611930022073-b7a4ba5fcccd'),
    specs: { ram: '12 Go', storage: '256 Go', screen: '6.78"', battery: '4600 mAh' },
    stock: 21,
    rating: 4.3,
    is_featured: 0,
  },
  {
    name: 'فيفو Y36',
    name_fr: 'Vivo Y36',
    brand: 'Vivo',
    category: 'smartphones',
    price_dzd: 31000,
    old_price_dzd: null,
    description: 'متانةMIL-STD وبطارية كبيرة، هاتف متين للاستعمال اليومي في كل الظروف.',
    description_fr: "Certifié MIL-STD et grande batterie : un téléphone taillé pour le quotidien.",
    image_url: img('1598327105666-5b89351aff97'),
    specs: { ram: '6 Go', storage: '128 Go', screen: '6.64"', battery: '5000 mAh' },
    stock: 29,
    rating: 4.0,
    is_featured: 0,
  },
  {
    name: 'ون بلس نورد 3',
    name_fr: 'OnePlus Nord 3',
    brand: 'OnePlus',
    category: 'smartphones',
    price_dzd: 89000,
    old_price_dzd: 95000,
    description: 'معالج Dimensity 8200، شاشة AMOLED 120Hz وشحن فائق 100W. أداء رائد بسعر متوسط.',
    description_fr: "Dimensity 8200, AMOLED 120 Hz et charge 100 W : des performances flagship à prix moyen.",
    image_url: img('1592286927505-2fd0d8a2b1a4'),
    specs: { ram: '12 Go', storage: '256 Go', screen: '6.74"', battery: '4600 mAh' },
    stock: 11,
    rating: 4.6,
    is_featured: 1,
  },
  {
    name: 'نوكيا G42 128GB',
    name_fr: 'Nokia G42 128 Go',
    brand: 'Nokia',
    category: 'smartphones',
    price_dzd: 24000,
    old_price_dzd: null,
    description: 'تحديثات أمان لمدة 3 سنوات، بطارية قابلة للاستبدال وتصميم متين.',
    description_fr: "3 ans de mises à jour de sécurité, batterie remplaçable et coque solide.",
    image_url: img('1523206489230-c012c64b2b48'),
    specs: { ram: '6 Go', storage: '128 Go', screen: '6.56"', battery: '5000 mAh' },
    stock: 33,
    rating: 3.9,
    is_featured: 0,
  },
  // -------------------------------------------------------------------- laptops
  {
    name: 'ماك بوك إير M2 13 بوصة',
    name_fr: 'MacBook Air M2 13 pouces',
    brand: 'Apple',
    category: 'laptops',
    price_dzd: 245000,
    old_price_dzd: 265000,
    description: 'شريحة M2، هيكل ألومنيوم خفيف وبطارية تدوم حتى 18 ساعة. مثالي للدراسة والعمل.',
    description_fr: "Puce M2, châssis aluminium léger, jusqu'à 18 h d'autonomie : idéal étude et travail.",
    image_url: img('1517336714731-489689fd1ca8'),
    specs: { ram: '8 Go', storage: '256 Go', screen: '13.6"', battery: '52.6 Wh' },
    stock: 6,
    rating: 4.9,
    is_featured: 1,
  },
  {
    name: 'لينوفو ليجن 5 راپ 16GB',
    name_fr: 'Lenovo Legion 5 16 Go',
    brand: 'Lenovo',
    category: 'laptops',
    price_dzd: 189000,
    old_price_dzd: null,
    description: 'معالج Ryzen 7 وكارت رسومات RTX، شاشة 16 بوصة 165Hz للألعاب والمحترفين.',
    description_fr: "Ryzen 7, carte graphique RTX et écran 16 pouces 165 Hz pour le gaming et la création.",
    image_url: img('1541807084-5c52b6b3adef'),
    specs: { ram: '16 Go', storage: '512 Go', screen: '16"', battery: '80 Wh' },
    stock: 5,
    rating: 4.6,
    is_featured: 0,
  },
  {
    name: 'HP فيكتوس 15',
    name_fr: 'HP Victus 15',
    brand: 'HP',
    category: 'laptops',
    price_dzd: 135000,
    old_price_dzd: 148000,
    description: 'جهاز محمول متعدد الاستخدام للألعاب الخفيفة والعمل اليومي، شاشة 15.6 بوصة.',
    description_fr: "Portable polyvalent pour le jeu léger et le quotidien, écran 15,6 pouces.",
    image_url: img('1588872657578-7efd1f1555ed'),
    specs: { ram: '16 Go', storage: '512 Go', screen: '15.6"', battery: '70 Wh' },
    stock: 8,
    rating: 4.3,
    is_featured: 0,
  },
  // ---------------------------------------------------------------- accessories
  {
    name: 'سماعات أنكر باور frees Pro 2',
    name_fr: 'Anker Soundcore P2',
    brand: 'Anker',
    category: 'accessories',
    price_dzd: 8900,
    old_price_dzd: 11000,
    description: 'سماعات لاسلكية بخاصية عزل الضوضاء النشط وبطارية تدوم 30 ساعة مع العلبة.',
    description_fr: "Écouteurs sans fil à réduction de bruit active, 30 h avec le boîtier.",
    image_url: img('1606220945770-b5b6c2c55bf1'),
    specs: { ram: '-', storage: '-', screen: '-', battery: '30 h' },
    stock: 62,
    rating: 4.5,
    is_featured: 1,
  },
  {
    name: 'شاحن سريع أنكر 65W ثلاثي',
    name_fr: 'Chargeur Anker 65W 3 ports',
    brand: 'Anker',
    category: 'accessories',
    price_dzd: 5200,
    old_price_dzd: null,
    description: 'شاحن GaN بثلاثة منافذ، يشحن اللابتوب والهاتف والسماعات في نفس الوقت.',
    description_fr: "Chargeur GaN 3 ports : ordinateur, téléphone et écouteables en même temps.",
    image_url: img('1583394838336-acd977736f90'),
    specs: { ram: '-', storage: '-', screen: '-', battery: '65 W' },
    stock: 74,
    rating: 4.7,
    is_featured: 0,
  },
  {
    name: 'جراب حماية سامسونج-clear',
    name_fr: 'Coque de protection Samsung',
    brand: 'Samsung',
    category: 'accessories',
    price_dzd: 1800,
    old_price_dzd: 2500,
    description: 'جراب سيليكون مقاوم للصدمات مع حواف مرفوعة لحماية الكاميرا.',
    description_fr: "Coque silicone antichoc avec bords relevés pour protéger la caméra.",
    image_url: img('1572569511254-d8f925fe2cbb'),
    specs: { ram: '-', storage: '-', screen: '-', battery: '-' },
    stock: 120,
    rating: 4.0,
    is_featured: 0,
  },
  {
    name: 'ساعة ذكية هواوي GT4',
    name_fr: 'Montre connectée Huawei GT4',
    brand: 'Huawei',
    category: 'accessories',
    price_dzd: 34000,
    old_price_dzd: 38000,
    description: 'تتبع النوم والنشاط ومعدل ضربات القلب، مقاومة للماء وبطارية أسبوعين.',
    description_fr: "Suivi du sommeil, de l'activité et du rythme cardiaque, 2 semaines d'autonomie.",
    image_url: img('1546435770-a3e426bf472b'),
    specs: { ram: '-', storage: '4 Go', screen: '1.43"', battery: '14 jours' },
    stock: 17,
    rating: 4.4,
    is_featured: 0,
  },
  {
    name: 'باور بانك أنكر 20000mAh',
    name_fr: 'Batterie externe Anker 20000 mAh',
    brand: 'Anker',
    category: 'accessories',
    price_dzd: 6500,
    old_price_dzd: null,
    description: 'بطاقة متنقلة بسعة 20000mAh وشحن سريع 22.5W، مثالية للسفر.',
    description_fr: "Batterie externe 20 000 mAh, charge rapide 22,5 W, parfaite en voyage.",
    image_url: img('1590658268037-6bf12165a8df'),
    specs: { ram: '-', storage: '-', screen: '-', battery: '20000 mAh' },
    stock: 58,
    rating: 4.6,
    is_featured: 0,
  },
]
